spec/index.html, spec/source/conventions.html, spec/source/index.html
first draft of the migration...
=> fixes #8 migrating section 5 notational conventions

spec/index.html, spec/source/index.html, spec/source/locale-sensitive-functions.html
first draft of the migration...
=> fixes #16 migrating section 13 locale sensitive functions

spec/index.html, spec/source/index.html, spec/source/requirements.html
=> fixes #10 migrating section 7 requirements

spec/index.html, spec/source/collator.html, spec/source/index.html
first draft of the migration...
=> fixes #13 migrating section 10 Collator Objects

spec/source/negotiation.html
this is ready for review @rwaldron
=> fixes issue #12: Section 9 - Locale and Parameter Negotiation

spec/source/numberformat.html
this is one of the most complex sections, it is now ready for review. /cc @rwaldron
=> fixes issue #14: Section 11 - NumberFormat Objects

spec/source/datetimeformat.html
alright, final piece of the spec, only annexes are missing at this point. /cc @rwaldron
=> fixes issue #15: Section 12 - DateTimeFormat Objects

spec/source/collator.html, spec/source/datetimeformat.html, spec/source/numberformat.html
=> Migrate to <emu-table> & <emu-caption>. Closes gh-42

spec/collator.html, spec/conventions.html, spec/datetimeformat.html, spec/intl.html, spec/locale-sensitive-functions.html, spec/negotiation.html, spec/numberformat.html
The changes are for the most part only small bug fixes. I've split them into multiple commits, so it's easier to review them. Please let me know if any of the proposed changes are unclear.
=> Various fixes

spec/normative-references.html
https://github.com/tc39/ecma262/pull/300
=> Align normative external reference with ES2016: Unicode 8.0.0

spec/datetimeformat.html
DateTimeFormat.prototype.formatToParts()
* https://github.com/tc39/ecma402/pull/64
NumberFormat.prototype.formatToParts(): 
* https://github.com/tc39/ecma402/pull/79
These features are Stage 4, and are ready to be merged.
=> FormatToParts: aggregation of PR #64 and PR #79

spec/normative-references.html
…instead of a fixed version number.
Ref. https://github.com/tc39/ecma262/pull/620.
=> Normative: Require the latest available Unicode version

spec/datetimeformat.html, spec/index.html, spec/intl.html, spec/numberformat.html
CC @jswalden @anba Much of this is with respect to #84
=> Normative optional test tweaks

spec/numberformat.html
Fixes https://github.com/tc39/proposal-intl-plural-rules/issues/25
=> Add mxfdDefault to SetNumberFormatDigitOptions

README.md
They seem to have been moved to a new repo.
=> Minor update README for proposal repos

spec/collator.html, spec/datetimeformat.html, spec/numberformat.html
=> Normative: Make the prototypes ordinary objects

spec/conventions.html, spec/datetimeformat.html, spec/negotiation.html
Fixes #162 and addresses the remaining review comments from #155. Plus one or two unrelated fixes.
=> Read "hourCycle" options property once and fix some other issues

spec/intl.html
=> Editorial: Fix duplicate anchors

spec/datetimeformat.html, spec/intl.html, spec/numberformat.html
=> Editorial: Add note explaining legacy constructor path

spec/annexes.html, spec/collator.html, spec/conventions.html, spec/datetimeformat.html, spec/locale-sensitive-functions.html, spec/locales-currencies-tz.html, spec/negotiation.html, spec/numberformat.html
=> Editorial: Add backticks around strings

meetings/agenda-2018-02-16.md
Does this seem like a good start for the agenda for the meeting next Friday? Further PRs are always welcome.
cc @zbraniecki
=> February 2018 meeting agenda proposal

spec/pluralrules.html
s/SetNumberFormatOptions/SetNumberFormatDigitOptions/
=> Editorial: Make PluralRules point to the right algorithm

spec/pluralrules.html
=> Normative: Create the PluralCategories array each time

meetings/agenda-2019-01-17.md
=> Proposal agenda

meetings/agenda-2019-01-17.md
=> Revert "Proposal agenda"

meetings/agenda-2019-01-17.md
Restructure to add a "locale returned by resolvedOptions()" item and move #311  and #302 under it.
=> Add #311 and move # 302 down to group w/ it.

spec/negotiation.html
@littledan @anba @gsathya @Ms2ger 
Close https://github.com/tc39/ecma402/issues/223
=> Add step ResolveLocale 8.h.ii.2.b

meetings/agenda-2019-03-21.md
cc @sffc @littledan 
Not sure who to set as contact in this agenda, so far I just did a copy and paste from the previous agenda.
=> Create agenda page for March 2019

spec/annexes.html, spec/numberformat.html, spec/pluralrules.html
=> Fix small typos for the Unified NumberFormat parts

package.json
This is required to match changes from #415
=> Meta: Update ecmarkup to 3.19.1

spec/negotiation.html
Regression from #418. Sorry about that one!
=> Fix markup in ResolveLocale

package.json
=> Meta: Fix CI

package.json
=> Meta: Update travis-scripts for failure propagation

spec/numberformat.html
Fixes https://github.com/tc39/ecma402/issues/440
=> Editorial: fix ComputeExponent

spec/datetimeformat.html, spec/locale.html, spec/numberformat.html, spec/relativetimeformat.html
@anba @gibson042 @leobalter 
Reminded by @anba in https://github.com/tc39/ecma402/pull/459
=> Change url to https

README.md
=> Add link to PR and Proposal tracking wiki

spec/introduction.html, spec/metablock.html
I've contacted @sffc, @ryzokuken, and @gibson042 privately and got at least one +1 there.
I believe it's ok to have this PR open. The advisor role is uncommon in the spec but I believe it's fine.
=> Editorial: Update list of editors and advisor

spec/datetimeformat.html
Fixes #108.
Implements https://github.com/tc39/proposal-intl-datetime-style
=> Normative: Adding Intl.DateTimeFormat dateStyle/timeStyle specification.

spec/annexes.html, spec/collator.html, spec/datetimeformat.html, spec/listformat.html
=> Editorial: Mitigate current eckmarup warnings

.github/workflows/deploy.yml
Ref 946aa339e22d6a598a92493dd3488015f6ac700e
=> Meta: Fix gh-pages deploy action

spec/collator.html, spec/datetimeformat.html, spec/displaynames.html, spec/listformat.html, spec/numberformat.html, spec/pluralrules.html, spec/relativetimeformat.html
...to https: with trailing slash
=> Editorial: Normalize CLDR URLs

spec/metablock.html
=> meta: add ryzokuken to editors

spec/metablock.html
=> meta: update links for communications

spec/collator.html, spec/datetimeformat.html, spec/displaynames.html, spec/listformat.html, spec/locale.html, spec/numberformat.html, spec/pluralrules.html, spec/relativetimeformat.html
cf. https://github.com/tc39/ecma402/pull/553#issuecomment-1012508992
=> Linearize reading

spec/numberformat.html
Ref https://github.com/tc39/ecma262/pull/2711
=> Editorial: Improve consistency of referring to String values

.github/workflows/deploy.yml, package.json, spec/annexes.html, spec/collator.html, spec/conformance.html, spec/conventions.html, spec/datetimeformat.html, spec/index.html, spec/introduction.html, spec/locale-sensitive-functions.html, spec/locales-currencies-tz.html, spec/normative-references.html, spec/overview.html, spec/requirements.html
=> Prepare main branch to be ES2023

spec/datetimeformat.html, spec/negotiation.html
=> Editorial: Update DateTimeFormat to conform with arithmetic conventions

spec/negotiation.html
Ref https://github.com/tc39/proposal-temporal/pull/2243
=> Editorial: Extend GetOption to support a *"number"* type

spec/datetimeformat.html
=> Normative: Correct Gregorian calendar BC(E) era to signed years less than 1 AD

spec/annexes.html
Update the id to fix "lint & build / lint & build (push)" build breakage
=> Editorial: Fix --lint-spec --strict build error

spec/locale.html
=> Editorial: Correct the Intl.Locale.prototype.{script,region} algorithms

package-lock.json, package.json, spec/listformat.html
https://github.com/tc39/ecma262/pull/3268 added a new AO which lets us simplify use of the iteration protocol. This was the only use in 402.
=> Editorial: use new IteratorStepValue AO

spec/annexes.html, spec/collator.html, spec/datetimeformat.html, spec/listformat.html, spec/locale-sensitive-functions.html, spec/locale.html, spec/locales-currencies-tz.html, spec/negotiation.html, spec/numberformat.html, spec/pluralrules.html, spec/relativetimeformat.html, spec/segmenter.html
Last year @anba put up two extraordinary PRs, #826 and #827, that made major improvements across the spec as a whole. This PR is those PRs rebased onto the current main.
=> Editorial: Rebase of PRs #826 and #827

spec/durationformat.html
Ref #963
Ref #969
Thanks @trflynn89!
=> Editorial: Fix spec link for new ValidateDurationUnitStyle AO

spec/annexes.html, spec/collator.html, spec/conformance.html, spec/conventions.html, spec/datetimeformat.html, spec/displaynames.html, spec/index.html, spec/intl.html, spec/introduction.html, spec/listformat.html, spec/locale-sensitive-functions.html, spec/locale.html, spec/locales-currencies-tz.html, spec/metablock.html, spec/negotiation.html, spec/normative-references.html, spec/numberformat.html, spec/overview.html, spec/pluralrules.html, spec/relativetimeformat.html, spec/requirements.html, spec/scope.html, spec/segmenter.html
Spec file cleanup via `emu-format --write`.
=> Editorial: emu-format

spec/durationformat.html
=> Editorial: Explain ValidateDurationUnitStyle parameter "unit"

spec/intl.html
Frequently forgotten - I last did this in https://github.com/tc39/ecma262/pull/3456 :)
=> Editorial: Add Intl.DurationFormat to list of constructors

spec/durationformat.html
Fixes #965
Also includes independent commits with miscellaneous improvements.
=> Editorial: Replace DurationFormat [[${Unit}{Style,Display}]] slots with [[${Unit}Options]]

package-lock.json, package.json
Update ecmarkup to the latest version (21.2.0). It introduces interesting features like dark mode but doesn't seem to break anything.
=> Meta: update ecmarkup

spec/collator.html, spec/datetimeformat.html, spec/displaynames.html, spec/durationformat.html, spec/listformat.html, spec/locale.html, spec/negotiation.html, spec/numberformat.html, spec/pluralrules.html, spec/relativetimeformat.html, spec/segmenter.html
=> Editorial: Add an operation abstracting service constructor locale resolution

spec/locale.html
Ref https://github.com/tc39/ecma402/pull/1007#pullrequestreview-2883658270
=> Editorial: Clarify that duplicate-variants checks are case-insensitive
