tc39/ecma402

README.md

Ecma-402 LookupMatcher (9.2.2 and 9.2.3) fails to perform such task in some cases. This proposal fixes it. Please, see http://github.com/rxaviers/ecma402-fix-lookup-matcher for details.

Add proposal for fixing the LookupMatcher algorithm

---

README.md

Allows to select a rounding function for NumberFormat different than round "half-even". For example: ceil, floor, or truncate.
See: https://github.com/rxaviers/ecma402-number-format-round-option

Add proposal for Intl.NumberFormat round option

---

spec/source/index.html

@caridy newer versions of ecmarkup have replaced `<link ...>` with `<emu-import ...>`. This patch updates the spec source.

Migrate to <emu-import href="...">

---

spec/collator.html
spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/numberformat.html

- then and else corrections
- algos with numeric index in the steps are now set to 1.
- few missing cross-links
- proper use of `*this* value`
- ReturnIfAbrupt -> ?
- inline styles and conventions

editorial fixes and alignment with ES2016 conventions

---

package.json
spec/collator.html
spec/datetimeformat.html
spec/index.html
spec/locale-sensitive-functions.html
spec/negotiation.html
spec/numberformat.html

* function length and name clean-ups
* list argument should « _alway_ » have spaces.
* update headers to use spaces
* update optional arguments to have spaces
* https for `tc39.github.io`
Other changes:
* update ecmarkup
* fix link to license

Editorial: Fixes to align with ES2016 Draft 2016-01-20

---

spec/datetimeformat.html
spec/numberformat.html

__Disclaimer: This PR does not modify any algo, we just reshuffle them for organizational purposes.__
* "Number Format Functions" holds several abstract operations, and it was a sub-section under "Properties of the Intl.NumberFormat Prototype Object", which is confusing, specially once we add more properties to those objects that could call the same abstract operations. The same applies to "DateTime Format Functions".
* `InitializeNumberFormat()` and `InitializeDateTimeFormat()` abstract operations were under the corresponding constructor section.
* moving all abstract operations of NumberFormat Objects into an abstract sub-section
* moving all abstract operations of DateTimeFormat Objects into an abstract sub-section.
* https://rawgit.com/caridy/c80267817f2736db7de8/raw/f7df1b2c9de232a69d …

Refactor to group abstract operations per section for `NumberFormat` and `DateTimeFormat`

---

spec/intl.html

Feature from https://github.com/tc39/ecma402/issues/46
This is probably the only new feature we will be able to get into 3rd edition.
This PR also opens the door for adding more function properties to `Intl` in the future, very similar to `Math` in 262.
/cc @littledan @zbraniecki @ericf @rwaldron

Exposing `CanonicalizeLocaleList()` abstract operation via `Intl.getCanonicalLocales()`

---

spec/conventions.html
spec/negotiation.html

Add the supported Unicode locale extension sequence at the end of the
'foundLocale' language tag, but before any private-use sequence. Also
call CanonicalizeLanguageTag to ensure the newly formed language tag
is canonicalized (This step is only required for implementations which
implement the optional Unicode locale extension canonicalization from
RFC6067 and when the 'relevantExtensionKeys' list is not sorted.).
Fixes https://bugs.ecmascript.org/show_bug.cgi?id=1456

Ensure ResolveLocale with BestFitMatcher returns valid language tags

---

package.json
spec/annexes.html
spec/collator.html
spec/conventions.html
spec/datetimeformat.html
spec/index.html
spec/locale-sensitive-functions.html
spec/negotiation.html
spec/numberformat.html

* all links to be lowercase (to match 262)
* all reference to ES2016 should use `<emu-xref>`
* supersede methods from 402 should be linkable (using "sup-" prefix instead of "sec-" for those)
* correct spacing on headers and invocations
* consistently use a comma before "the following steps are taken"

[Editorial] improving cross linking and other small things

---

spec/datetimeformat.html

Related issue: https://github.com/tc39/ecma402/issues/88

Intl.DateTimeFormat should localize era names as well

---

spec/collator.html
spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/negotiation.html
spec/numberformat.html

This is a follow up from https://github.com/tc39/ecma262/pull/591
Specifically, change:
```
the [[Foo]] internal slot of _O_  (132 occurrences)
```
and
```
_O_'s [[Foo]] internal slot (265 occurrences)
```
to
```
_O_.[[Foo]]
```
while preserving some references when using "Internal Slot" in a sentence to test for identity, and removing "the value of" wording in front.
This is a follow up from https://github.com/tc39/ecma262/pull/597
* removing unnecessary definitions

Editorial: use dot notation for accessing internal slots & co.

---

spec/numberformat.html

Based on my last conversation with Allen, we can preserve all the internal changes to accommodate `formatToParts` without having to expose the new API. Let's continue with the editorial changes until we can get this restock again.

Fixes issue #101: temporarily removing Intl.NumberFormat.prototype.formatToParts()

---

spec/numberformat.html

This will allow us to not have to initialize NumberFormat in PluralRules - https://github.com/tc39/proposal-intl-plural-rules/pull/15
@caridy - can you review? I'm wondering if we should name the first parm `options` instead of `numberFormat`.
@eemeli - does it look good to you?

Separate out FormatNumberString operation

---

spec/numberformat.html

This will allow us to format the same options in PluralRules and later in other formatters.

Add Abstract function SetNumberFormatDigitOptions

---

spec/numberformat.html

I'm implementing the `SetNumberFormatDigitOptions` as part of the https://bugzilla.mozilla.org/show_bug.cgi?id=1270146 and noticed that this regresses `NumberFormat`.
What happens is that if the user doesn't manually pass `minimumFractionDigits` option, `minimumFractionDigits` doesn't have the default value in `SetNumberFormatDigitOptions` and `mnfd` ends up being `undefined`.
Then, `mnfd` is passed as the third argument to `GetNumberOption` for `maximumFractionDigits` and that fails the assertion that the third argument is a number.
This patch fixes the bug and also shifts the order of operations in `SetNumberFormatDigitOptions` to better replicate previous behavior with regards to `*SignificantDigits` - the two values were not set at all on the `intlObj` if they were not passed in …

Add mnfdDefault to SetNumberFormatDigitOptions

---

spec/numberformat.html

Looks like someone decided *style* was a good name, then only half-converted things, I guess?  I could also make the name *s* if desired, but the longer name seems slightly better (except to the extent that prior spec versions used *s* as the name).

Consistently use the name `style` for the variable denoting format style in `InitializeNumberFormat`

---

spec/numberformat.html

SetNumberFormatDigitOptions is fallible when provided a user-controllable options object, so invoke it as such.  (This change is also needed in [caridy/intl-plural-rules-spec](https://github.com/caridy/intl-plural-rules-spec), if the person who takes this has access to that spec as well.)

Invoke `SetNumberFormatDigitOptions` as fallible in `InitializeNumberFormat`

---

spec/conventions.html
spec/datetimeformat.html
spec/index.html
spec/intl.html
spec/numberformat.html

This patch addresses #57 by allowing certain legacy constructor
patterns to coexist with the new guarantees in ECMA-402 v2, which
allows for a pattern where all internal slots exist from the
beginning of the object's lifetime. The compromise is based on
storing a "real" object inside of a symbol-named property to allow
for object initialization in cases of the
Intl.<constructor>.call(Object.create(Intl.<constructor>) pattern.
Legacy methods have to forward their calls to this "real" object.
This patch specifies the change for Intl.NumberFormat, but an
analogous change would also be needed for Intl.DateTimeFormat and
Intl.Collator. This version is being sent out for review for feedback
from users and implementors. A sample implementation in V8 can
be found at …

ECMA-402 v1 legacy constructor semantics compromise

---

spec/negotiation.html
spec/numberformat.html

This patch refactors NumberFormat's option parsing code to avoid
redundant Get calls for {minimum,maximum}SignificantDigits .
Fixes #131

Normative: Avoid reading options twice

---

spec/datetimeformat.html

This is specified by marking the argument as not optional, which
makes its implicit length 1, according to notational conventions.
Closes #133

Normative: Intl.DateTimeFormat.prototype.formatToParts.length is 1

---

package.json

The `test-travis` branch does not exist.
This hopefully fixes #142.

Remove `git checkout -q test-travis` from build

---

spec/annexes.html
spec/datetimeformat.html

That's the first step to fix #105

Support hc extension key in DateTimeFormat.

---

spec/collator.html
spec/conventions.html
spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/normative-references.html
spec/numberformat.html
spec/requirements.html

Applies on top of #155 (there is a way not to include the commits from #155 here, isn't it?).
fcd6157224e759f73602e03b8112330044c22380 replaces all internal arrays with lists (and objects with records) to fix #156. The commit has a mix of &lt;fieldName&gt; and &amp;lt;fieldName&amp;gt; because I tried to stick with the form which was already used in the algorithms.
And while going through the spec, I couldn't help myself to fix some editorial nits: a9492cb800f6cc5181e51743e61bde9485deb6a7.

Use lists and records for all internal data

---

spec/collator.html
spec/conventions.html
spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/normative-references.html
spec/numberformat.html
spec/requirements.html

I started these changes for the 2017 release, but I didn't finish it in time, so it is possible that some of the algorithm conventions used are no longer correct. 
And I'm not 100% happy with the new UnicodeExtensionValue operation, because the string index operations still feel a bit too low-level and a more abstract definition is probably easier to understand, but I still think it makes sense to have a separate abstract operation to get the Unicode extension value for a specific key.

Editorial and normative changes from an unfinished ES2017-Intl review

---

spec/introduction.html

* Aligning with the intro in 262
* Adding edition logs
* Adding editors' list without contributors since the list keeps growing (we can point to github history)

[Editorial] intro

---

spec/datetimeformat.html

c8b9f6e5714c14e4bfd253d02db5d8271d175685
- The "hourCycle" and "hour12" options should always be retrieved and validated from the options object, even when the resolved pattern doesn't contain an "hour" property.
- Otherwise invalid but unused "hourCycle" and "hour12" options aren't rejected,
- and implementations would be forced to resolve the pattern before processing "hourCycle" and "hour12".
4d771c8ef6d09320b6615a22e3a612cbc625b38c
- If an option can be set through a normal option and a Unicode extension value, the normal option should always have precedence over the Unicode extension value (cf. ResolveLocale [1]).
- That means "hourCycle" needs to be retrieved from the options object before calling ResolveLocale (right now https://tc39.github.io/ecma402/#sec-initializedatetimeformat …

Correctly retrieve hourCycle/hour12 from options and Unicode extension value

---

spec/locale-sensitive-functions.html

Also added note about the effective difference between this algorithm and the version from ECMA-262.
See https://github.com/tc39/ecma262/pull/662 for the update to ECMA-262's version.
Fixes #173

Editorial: Update Array.prototype.toLocaleString to mirror the algorithm in ECMA-262. (Fixes #173)

---

spec/collator.html
spec/datetimeformat.html
spec/numberformat.html

This internal slot has not done anything since ECMA 402 v1.
This patch simply removes it.
Closes #115

Editorial: Remove [[InitializedIntlObject]] internal slot

---

spec/numberformat.html

`Intl.NumberFormat.formatToParts` was first propsed in #30. The spec for it was created in #79 and merged in #100 (with follow-ups). Due to browser implementations not being ready at the time, it was moved back to Stage 3 in #101.  The internal refactoring were kept in master and the user-facing method `formatToParts` was removed from the spec in #102.
As of August 1st, 2017, `Intl.NumberFormat.prototype.formatToParts` has shipped in two engines (behind a flag): [SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1289882) and [V8](https://bugs.chromium.org/p/v8/issues/detail?id=5244).  This PR brings `Intl.NumberFormat.formatToParts` back as Stage 4 proposal.
> const usd = Intl.NumberFormat('en', { style: 'currency', currency: 'USD' });
> usd.format(123456.789)
'$123,456.79'
> …

Re-expose Intl.NumberFormat.formatToParts

---

spec/collator.html
spec/normative-references.html

- `cldr.unicode.org` doesn't accept https.
- `https://www.unicode.org/versions/Unicode10.0.0/` is reachable per https, but the redirect from `https://www.unicode.org/versions/latest` goes to the http version

Change link addresses to https where possible

---

spec/collator.html
spec/numberformat.html

If an options object is not passed in, then use the default options
rather than querying for possible overrides in Object.prototype.
There are a couple points of motivation here:
- It is simpler to not fall back to Object.prototype, and the fallback
there feels unexpected.
- WebIDL dictionaries default to not reading Object.prototype; it
is nice to have consistency here.
- Real engine implementations were not consistently implementing the
fallback for certain paths, such as Number.prototype.toLocaleString
and String.prototype.localeCompare, where it is possible to observe
some invalid caching which would become valid with this patch
- DateTimeFormat already does not look to Object.prototype for defaults.
Closes #123
cc @anba

Normative: Use a null prototype for the default options

---

spec/overview.html

Articulation of goals as ECMA 402 evolves, meant to address
Microsoft's concerns about making a separate, compatible implementation.

Editorial: Describe intentions for compatibility across implementations

---

spec/collator.html
spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/numberformat.html

66b872f79f2ccff5259896a5728af47fa351cc41:
- Arbitrary objects can no longer be initialized as Intl object instances, so we can remove the phrases "xyz has been successfully initialized as a Collator/NumberFormat/DateTimeFormat". 
- I've also aligned the type tests for Intl objects to only test for the presence of the `[[Initialized<...>]]` internal slots. Newer code only tested for the presence of these slots, whereas older code still tested that the value of the internal slot is `true`.
- The initial value of `[[Bound<...>]]` internal slots is already `undefined`, so we can also remove the additional assignment. 
- And some drive-by fixes.
22d11efe64383659a63e94a50be059fa1c112d11:
- FormatNumberToString will also be called with Intl.PluralRules objects, so we shouldn't assert that the …

Remove notion of "objects initialized as Collator/NumberFormat/DateTimeFormat"

---

README.md

Apparently we misunderstood the decision at the September meeting and RTF is still at Stage 2.

Drop RelativeTimeFormat to stage 2

---

spec/collator.html
spec/datetimeformat.html
spec/numberformat.html

037a18ed4e4d62fc6249691e5aaedea3744b2008
Because the current algorithms don't explicitly specify in which order the properties are added, the new algorithms are a bit ugly, especially for `Intl.Collator` with its optional internal slots. :disappointed: 
We should probably fix this and add the properties in a specific order.
568e7bdbfd951853ff5f527ba5616b8ccb91e9ca 
No longer needed with the previous commit. Other, non-normative uses of these terms are removed in the next commit.
cf2b87144b953e4b3e31d7e238b6f35c1b99bb2e
So the preamble matches the current style. Also rephrases and moves a note for the DateTimeFormat bound function to the correct position.
a528cd9d4bc6d1608d6895ee2137701388d15994
IMO the `hour12` property note shouldn't be exclusively about web-compatibility, so I rephrased …

Add algorithms for resolvedOptions()

---

spec/datetimeformat.html

Fixes #192 
This change will limit the maximum allowed date-time value and aligns the limit with `Date`.
```js
var dtf = Intl.DateTimeFormat("en-US");
print(dtf.format(8640000000000000 - 1)); // 9/13/275760
print(dtf.format(8640000000000000)); // 9/13/275760
print(dtf.format(8640000000000000 + 1)); // <-- Throws a RangeError with the proposed patch!
```
```js
print(new Date(8640000000000000 - 1).getTime()); // 8639999999999999
print(new Date(8640000000000000).getTime()); // 8640000000000000
print(new Date(8640000000000000 + 1).getTime()); // NaN
```

Normative: Apply TimeClip in PartitionDateTimePattern.

---

spec/pluralrules.html

Editorial fix for PluralRules; should consider backporting to ES2018

Editorial: Use OrdinaryCreateFromConstructor properly

---

spec/numberformat.html

Normative: Treat -0 as negative in NumberFormat

---

spec/datetimeformat.html
spec/numberformat.html

In practice, libraries which underly ECMA-402 implementations may
implement much of algorithms such as PartitionNumberFormat and
PartitionDateTimeFormat. Sometimes, patterns from these algorithms
will include unexpected fields. To handle these cases, this patch
adds logic to represent them literally in the output of `format`
methods. `formatToParts` methods use the "unknown" field type.
This patch includes additional editorial/typo fixups:
- Remove the previous logic to leave unrecognized fields in patterns
in place (logic which was broken in DateTimeFormat)
- Define ILD and ILND inline, to reduce confusion
- Include some missing words in comparison
Closes #231

Normative: Permit "unknown" DateTimeFormat/NumberFormat fields

---

spec/datetimeformat.html
spec/numberformat.html

Editorial: Add a note to Intl.NumberFormat.prototype.format about the strange binding.

---

spec/numberformat.html

This was added in 94045d234762ad107a3d09bb6f7381a65f1a2f9b.

Normative: Remove stray comma from string in SetNumberFormatDigitOptions().

---

spec/collator.html
spec/datetimeformat.html
spec/numberformat.html
spec/pluralrules.html

Each place that tables are traversed, it is now specified to be in
the order that the table was written, as opposed to being ambiguous
as previously:
- In resolvedOptions, this is observable in the order of keys
- In the DateTimeFormat constructor, this is observable in the order
of property Get calls
Closes #264

Normative: Specify order of table traversal

---

spec/negotiation.html

This array has nonwritable, nonconfigurable elements to future-proof
for a path that it doesn't seem like we're planning on going down.
Make it an ordinary Array instead, as suggested by @jakobkummerow.
Closes #258

Normative: Don't harden supportedLocalesOf Array

---

.npmrc

I'd like to avoid listing this file as untracked after each npm install usage.

Add package-lock.json

---

.travis.yml
package.json
spec/introduction.html
spec/metablock.html

The Release Candidate for the ES2019 Edition is at https://github.com/tc39/ecma402/tree/es2019
This PR has the same commits but the one adding the Release Candidate status, following the style I've identified for es2018.
I should follow up with the proper bumps to set es2020

Bump es2019

---

spec/locales-currencies-tz.html

Ref #330 
cc @anba @sffc @FrankYFTang 
This is a tentative to update the immediate parts of #330, please let me know WDYT?

Normative: Apply recommended updates for BCP 47 Locale Identifiers

---

CONTRIBUTING.md
README.md
meetings/agenda-2018-01-19.md
meetings/agenda-2018-02-16.md
meetings/agenda-2018-03-16.md
meetings/agenda-2018-04-20.md
meetings/agenda-2018-05-17.md
meetings/agenda-2018-10-18.md
meetings/notes-2017-12-15.md
meetings/notes-2018-01-19.md
meetings/notes-2018-02-16.md
meetings/notes-2018-03-16.md
meetings/notes-2018-04-20.md
meetings/notes-2018-05-17.md
meetings/notes-2018-06-15.md
meetings/notes-2018-08-16.md
meetings/notes-2018-10-18.md
spec/collator.html
spec/datetimeformat.html
spec/locales-currencies-tz.html
spec/normative-references.html
spec/numberformat.html
spec/pluralrules.html

Ref #330 
cc @anba 
---
There are still some http links that I couldn't find any alternative using https. Mostly for cldr.unicode.org.

Editorial: Prefer ssl links over regular http

---

spec/locale-sensitive-functions.html

This is a new PR after feedback from @littledan's original fix #291 
The feedback in #299 and discussed in the [2018-11-26 meeting](https://github.com/tc39/ecma402/blob/b7ace4ce6d6fe6598f3f16536d42f7c8fd95258e/meetings/notes-2018-11-26.md) was to:
1. Allow any custom tailoring, not only the Unicode Database.
2. Mandate the implementations consistently use the same case mapping for the same locale.

Normative: Permit use of implementation-defined tailoring for case mapping

---

spec/locale-sensitive-functions.html
spec/numberformat.html

This patch brings Intl.NumberFormat support to BigInt, and
adds a BigInt.prototype.toLocaleString method based on it.
The design here is to include overloading between BigInt and Number
as arguments for the format and formatToParts methods based on
ToNumeric. This means that, for example, string arguments are
cast to Number, rather than BigInt. This design preserves
compatibility and consistency with operators like unary -
This definition permits options in the NumberFormat to force
decimal places, e.g., 1n formatting as 1.00000 if the minimum
fractional digits is 5. Alternative semantics would be to
throw an exception in this case.
For the algorithm text itself: the specification algorithms
ToRawPrecision and ToRawFixed are now used for both Numbers
and BigInts. Given the ECMAScript …

Normative: Support BigInt in NumberFormat and toLocaleString

---

spec/datetimeformat.html

This PR should not change the outcome of this abstract operation. The intent of these changes is only to make clear which algorithms to use for which values from [ECMA-262's date-values-from-time algorithms](https://tc39.github.io/ecma262/#sec-overview-of-date-objects-and-definitions-of-abstract-operations).
Here is the html for easy reading:
https://spectranaut.github.io/ecma402/#sec-tolocaltime

Editorial: clarification how to calculate gregorian date and time values

---

spec/datetimeformat.html

This commit was missing from the merged PR: https://github.com/tc39/ecma402/pull/348
Relevant discussion: https://github.com/tc39/ecma402/pull/348#discussion_r307534254

Editorial: add [[era]] calculation for gregorian date

---

spec/datetimeformat.html
spec/negotiation.html
spec/numberformat.html

The PartitionNumberPattern and PartitionDateTimePattern algorithms contain
substantively similar prose to iterate over a string of the form
"aaa{property}bbb". Extracting this from from the domain-specific prose
makes all three algorithms more readable.

Editorial: Extract pattern string handling into an abstract method

---

spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/numberformat.html

This is not strictly necessary, as it can be interpreted as returning the
Completion Record. However, using the question mark seems to be the more
common approach.

Editorial: Add question marks to Format calls.

---

docs/style-guide.md

Follow-up to https://github.com/tc39/proposal-intl-displaynames/issues/32.

Editorial: Adding style-guide.md with casing conventions explainer.

---

spec/datetimeformat.html

These fields are present in, e.g., some Chinese calendars.
Broken out from #227. Fixes part of #225.

Normative: Permit relatedYear and yearName in output

---

spec/collator.html
spec/datetimeformat.html
spec/numberformat.html
spec/pluralrules.html

Ref #386
The consistency matches the text from ECMA-262
cc @anba @gibson042

Editorial: Fix consistency over instances that are ordinary objects

---

spec/annexes.html
spec/collator.html
spec/conventions.html
spec/datetimeformat.html
spec/intl.html
spec/locale-sensitive-functions.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html

This follows the convention set in ECMA-262 to format strings as literals (`*"string*"` instead of ``` `"string"` ```, see PR: https://github.com/tc39/ecma262/pull/1733) and closes https://github.com/tc39/ecma402/issues/54.
There is also one commit that adds a link in [5. Notational Conventions](https://tc39.es/ecma402/#conventions) to ECMA-262.
While reviewing, consider the following conventions from ECMA-262 that I'm not positive apply here:
- [Tilde for spec-interal values](https://github.com/tc39/ecma262/pull/1725): I couldn't find an example of a spec internal value in ECMA-402 that is not also a string specified somewhere else, such as the  IANA Time Zone Database or Unicode. Because the string is not an internal arbitrary value it doesn't seem like we should use `~`.
- [Notation …

Editorial: Stylize strings as values.

---

spec/negotiation.html

Right now after the loop finishes, the remainder is
`pattern.substring(nextIndex + 1, len)` (bc it's exclusive) but should
be `pattern.substring(nextIndex, len)` instead since `nextIndex` is
already set to `endIndex + 1` in the loop.
Take `AA{0}BB` as an example, after the loop finishes:
- beginIndex = -1
- endIndex = 4
- nextIndex = 5
so `pattern.substring(5, 7)` yields `BB` (correct) vs the old behavior
would just yield `B`
Reference impl: https://github.com/formatjs/formatjs/blob/master/packages/intl-utils/src/polyfill-utils.ts#L220
Reference test: https://github.com/formatjs/formatjs/blob/master/packages/intl-utils/tests/polyfill-utils.ts

Editorial: Fix off-by-1 error in PartitionPattern

---

spec/datetimeformat.html

In CLDR, the set of patterns is based on the the calendar, not
simply the language-region-script. Previously, however, the set
was based purely on the base name. This patch switches to a two-level
lookup to permit implementations to have more accuracy.
Splitting off part of #227. Fixes part of #225.

Normative: Allow calendar to determine choice of pattern

---

spec/conventions.html
spec/index.html
spec/relativetimeformat.html

Adding specification text from https://github.com/tc39/proposal-intl-relative-time to the main spec.

Normative: Adding Intl.RelativeTimeFormat specification

---

spec/annexes.html
spec/collator.html
spec/conformance.html
spec/conventions.html
spec/datetimeformat.html
spec/intl.html
spec/locale-sensitive-functions.html
spec/numberformat.html
spec/pluralrules.html

To be consistence internally and with all the changes in ECMA-262.

Editorial: Use string notation for properties

---

spec/annexes.html
spec/locales-currencies-tz.html
spec/numberformat.html
spec/pluralrules.html

This PR is to merge the Unified Intl.NumberFormat proposal into ECMA-402, pending final Stage 4 approval.
https://github.com/tc39/proposal-unified-intl-numberformat

Add Unified Intl.NumberFormat proposal to ECMA-402.

---

spec/datetimeformat.html
spec/locales-currencies-tz.html
spec/numberformat.html

This patch allows calendar and numberingSystem to be specified in
the options bag of the DateTimeFormat and NumberFormat constructors.
One use case for these options would be, when working with locales
which have two numbering systems and calendars in use--the UA default
may be the non-Western one, but in some contexts, it may be appropriate
to use the Western one. Currently, without the patch, it would be
necessary to parse the BCP 47 language tag in the application, but Intl
provides no library to do so. For example, this all occurs in this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1370086
Related bug: #105 . This patch leaves out "collation" because of a lack
of clear use cases.

Normative: Add calendar and numberingSystem options

---

spec/locale-sensitive-functions.html

For consistency, the references go to ECMAScript 2020 (the 262 candidate edition in parallel)

Typo 2019 => 2020

---

spec/biblio.json

- Remove obsolete links to BigInt proposal and use ecma262 instead
- Update spec website url to `https://tc39.es/ecma262/`

Editorial: Update biblio

---

spec/relativetimeformat.html

Add text about the length property of supportedLocalesOf in RelativeTimeFormat to make it consistent with other parts.
Ref
https://tc39.es/ecma402/#sec-intl.collator.supportedlocalesof
https://tc39.es/ecma402/#sec-intl.numberformat.supportedlocalesof
https://tc39.es/ecma402/#sec-intl.datetimeformat.supportedlocalesof
https://tc39.es/ecma402/#sec-intl.pluralrules.supportedlocalesof
https://tc39.es/ecma402/#sec-Intl.RelativeTimeFormat.supportedLocalesOf

Add length property of RelativeTimeFormat

---

spec/numberformat.html

Add more numbering systems which on CLDR 37
Close https://github.com/tc39/ecma402/issues/437

Update Table 4 Numbering systems

---

spec/annexes.html
spec/collator.html
spec/datetimeformat.html
spec/numberformat.html
spec/pluralrules.html

Resolves #176.
If this reaches consensus, I will proceed with `test262` coverage and WebKit implementation.
_cc_ @littledan @Ms2ger

Normative: Make @@toStringTag values more meaningful

---

spec/locale.html
spec/negotiation.html

In Temporal, we are using an operation similar to GetOption (and intend
to add it to 262 in the future) and it came up in a discussion that it
would be better to have this assertion in GetOption to show that all
call sites should perform ToObject or whatever on the options object.
Assertion also added to GetNumberOption for symmetry, and to
ApplyOptionsToTag for clarity.

Editorial: Add type assertion to GetOption

---

spec/overview.html

Add a brief note to the specification about the reason for non-existence
of parsing functionality.
Fixes: https://github.com/tc39/ecma402/issues/424
/cc @sffc @littledan

editorial: add note about parsing

---

spec/datetimeformat.html
spec/negotiation.html
spec/numberformat.html

Reduce double negative in the spec.
See also https://github.com/tc39/ecma402/issues/458

Editorial: Change If X is not undefined

---

spec/collator.html
spec/datetimeformat.html
spec/numberformat.html

I noticed we're not consistent about whether we write
> Let foo be *this* value
vs
> Let foo be the *this* value
262 consistently uses the latter form, so this PR just unifies to that language.

Editorial: Change "be this value" to "be the this value"

---

spec/annexes.html
spec/intl.html

Consensus: https://github.com/tc39/ecma262/pull/2057#issuecomment-661259830.
Tests: https://github.com/tc39/test262/pull/2712.

Normative: Define @@toStringTag for Intl namespace object

---

spec/conformance.html

Ref #427
cc @sffc @anba. This PR just adds what's initially proposed at #447, but it does not address removing extensions not used.
This can be eventually updated or discarded. It's intentionally not set to **Fix** or **Close** the original issue.

Editorial: Update Conformance Section

---

package.json
spec/annexes.html
spec/collator.html
spec/conformance.html
spec/datetimeformat.html
spec/intl.html
spec/locale-sensitive-functions.html
spec/locale.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/normative-references.html
spec/numberformat.html
spec/overview.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/scope.html

Based on a [discussion in Temporal](https://github.com/tc39/proposal-temporal/pull/870), it seems like it might be a good idea to run ecmarkup's linter on the spec, now that in version 4.1.0 has brought several bug fixes in the linter.
This adds the linter to the build process and makes it fail if any warnings are generated.

Editorial: Fix linter errors in spec

---

CONTRIBUTING.md

Adding guidelines for proposals in CONTRIBUTING.md

---

CONTRIBUTING.md

Meta: Add condition to prior art in CONTRIBUTING.md

---

spec/locale.html
spec/negotiation.html

I found it hard to follow the current algorithm, which uses three variables to track the current keyword, two of which are introduced inside a loop for use in later iterations _of_ the loop.

Editorial: Tweak UnicodeExtensionComponents to clarify spec variables

---

spec/collator.html

Collator already have "co" in  [[RelevantExtensionKeys]] internal slot and therefore the  usage by using "-u-co-$collationkey" is already supported in ECMA402.
This PR will also make our extension / option handling in ECMA402 consistent.
I check other object and I believe this is the only inconsistent handling between u extension and option now.
Close #380

Normative: Allow Collator to get collation from option

---

spec/annexes.html
spec/numberformat.html

Handle awkward rounding behavior when dealing with currencies and the
value of "maximumFractionDigits" is less than `cDigits`.
Fixes: https://github.com/tc39/ecma402/issues/239
Test 262 PR: https://github.com/tc39/test262/pull/2707
V8 CL: https://chromium-review.googlesource.com/c/v8/v8/+/2288710
/cc @sffc @littledan

Normative: handle awkward rounding behavior

---

spec/conformance.html

Closes #521
Technically this is normative, but remains within the consensus from DisplayNames, in my understanding.
cc @FrankYFTang

Normative: DisplayNames styles and type options as impl. defined

---

spec/datetimeformat.html

This commit restores a line I removed by accident when fixing merge conflicts for the fractionalSecondDigits PR.
Ref a6a16fa15ccf55e730f1c52955dd7ca921a88e0e

Editorial: Restore line removed by accident

---

spec/collator.html
spec/locale.html
spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html

Editorial: GetOption reform

---

spec/locales-currencies-tz.html

That is, because `en-emodeng-emodeng` with duplicated `emodeng` variant is not structurally valid, neither ought `de-t-en-emodeng-emodeng` be valid.  This fixes one of the issues raised in https://github.com/tc39/ecma402/issues/330.
This patch's wording (and how it talks about restrictions on subtag sequences) is somewhat messy.  Suggestions obviously appreciated for how to do this more clearly or concisely.

Normative: Do not allow duplicate variants within the `tlang` component of a `transformed_extensions`

---

spec/datetimeformat.html
spec/numberformat.html

This PR reduces the surface area of [legacy constructor semantics](https://github.com/tc39/ecma402/pull/84) by using [`OrdinaryHasInstance`](https://tc39.es/ecma262/#sec-ordinaryhasinstance) instead of [`instanceof` operator](https://tc39.es/ecma262/#sec-instanceofoperator), which skips `Symbol.hasInstance` lookup/call and a few checks we don't need or already implement.
The change is safe because a) `Symbol.hasInstance` is rarely used and b) the code that depends on [legacy constructor semantics](https://github.com/tc39/ecma402/pull/84) precedes cross-browser `Symbol.hasInstance` implementation.
JSC already implements this change, while V8 and SpiderMonkey perform [`InstanceofOperator`](https://tc39.es/ecma262/#sec-instanceofoperator).
<details>
<summary><code>Intl.NumberFormat</code> …

Normative: Use OrdinaryHasInstance in normative optional steps

---

spec/datetimeformat.html

Fix #188
Based on https://github.com/tc39/proposal-intl-DateTimeFormat-formatRange

Normative: Adding Intl.DateTimeFormat formatRange/formatRangeToParts specification

---

spec/displaynames.html
spec/listformat.html

Fix ECMA 2021 additions (Intl.DisplayNames and Intl.ListFormat) to work
with the new, stricter GetOption. This no longer coerces non-null
primitives to objects and instead throws a TypeError.
Fixes: https://github.com/tc39/ecma402/issues/537
/cc @sffc @ptomato

spec: GetOption reform for ECMA 2021

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/require-allow-edits.yml
spec/annexes.html
spec/collator.html
spec/datetimeformat.html
spec/locales-currencies-tz.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html

This patch fixes warnings raised from the spec build

Editorial: Fix spec typos and GH Workflow

---

spec/locale.html
spec/relativetimeformat.html

Unify the option value calendar/collation/numberingSystem checking while referring to UTS35
Close #565
@ryzokuken @sffc @zbraniecki @leobalter @gibfahn

Editorial- Unify the option value referring UTS35

---

spec/locale-sensitive-functions.html
spec/locale.html
spec/negotiation.html

Close #559
Remove the misleading usage of the "first" substring which imply it is possible to have second or rest but under condition which are not possible.

Editorial: Remove the mention of the "the first substring"

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

I'd like to open this for discussion.
This ECMA-402 repo has a different aspect compared to 262 as we accept issues with feature suggestions in our issues tracker. I'm adapting the current templates from 262 here and we should eventually add templates for new proposals, ideas, etc.
The PR template has a downstream notice to avoid issues on the spec chaining, I should add ECMA-262 in that list.
I'd like to get an idea of how this group sees the proposed additions. We can merge it if useful.

Meta: Add templates for issues and PRs

---

spec/numberformat.html

Mention "cf" in https://tc39.es/ecma402/#sec-intl.numberformat-internal-slots
see also https://unicode.org/reports/tr35/#Key_Type_Definitions Make it clear that "cf" is not supported via extension.

Editorial: mention "cf" in Note 1 of #sec-intl.numberformat-internal-slots

---

spec/locales-currencies-tz.html

Address https://github.com/tc39/ecma402/issues/576

Normative: Add Lower case mapping definition in 6.1

---

spec/annexes.html

Clarify that "All registered Zone and Link names" is implementation dependent in a sense that a ealier shipped browser may not have the latest IANA timezone DB in practice.
(in ECMA262 language - implementation-approximated ??)

Editorial: Clarify the "All registered Zone and Link names"

---

package.json
spec/datetimeformat.html

Meta: Upgrade ecmarkup

---

spec/collator.html
spec/datetimeformat.html
spec/listformat.html
spec/locale.html
spec/relativetimeformat.html

This PR changes several instances of "[[Slot]][[&lt;_variable_&gt;]]" and "[[Slot]][&lt;_variable_&gt;]" to the proper "[[Slot]].[[&lt;_variable_&gt;]]" notation.
Thanks to @hackmud-dtr for noticing these.

Editorial: Normalize internal slot access

---

spec/datetimeformat.html

Prior to this commit, the variable named `prop` was not defined in two
of the loops within ToDateTimeOptions. Define it using the convention
for loops in ECMA262, and update the algorithm's similar loops to match.

Editorial: normalize property name iteration

---

spec/collator.html
spec/datetimeformat.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html

Some but not all `supportedLocalesOf` definitions explicitly specify `length`, but none of them should need to. However, we might consider updating https://tc39.es/ecma402/#conventions to explicitly adopt https://tc39.es/ecma262/#sec-ecmascript-standard-built-in-objects
> Every built-in <a href="https://tc39.es/ecma262/#function-object">function object</a>, including <a href="https://tc39.es/ecma262/#constructor">constructors</a>, has a **"length"** property whose value is a non-negative <a href="https://tc39.es/ecma262/#integral-number">integral Number</a>. Unless otherwise specified, this value is equal to the number of required parameters shown in the subclause heading for the function description. Optional parameters and rest parameters are not included in the parameter count.

Editorial: Remove unnecessary specification of supportedLocalesOf `length` properties

---

spec/collator.html
spec/datetimeformat.html
spec/displaynames.html
spec/listformat.html
spec/numberformat.html
spec/pluralrules.html

Ref https://github.com/tc39/ecma262/pull/2490

Editorial: Use consistent language to reference intrinsic constructors

---

spec/numberformat.html

I changed part of the ToRawPrecision algorithm in ES2019 as part of [Unified NumberFormat](https://github.com/tc39/proposal-unified-intl-numberformat).  However, in my work on NFv3, I realized that one change I made is unsound.  This is in a crucial function, ToRawPrecision, which is used for all significant digits rounding.
Problem explanation: In ToRawPrecision, the _e_ value is supposed to represent the power of 10 of the resolved number *after* rounding.  However, my change in ES2020 computed _e_ based on the input value *before* rounding.
Example values of _x_, _p_, _n_, and _e_, with _xFinal_ for reference:
Formula: _x_ ≈ _n_ × 10<sup>_e_–_p_+1</sup>
| _x_ | _p_ | _n_ | _e_ | _xFinal_ |
|---|---|---|---|---|
| 1.11 | 3 | 111 | 0 | 1.11 |
| 11.1 | 3 | 111 | 1 | 11.1 |
| 1.11 | 2 | 11 …

Normative: Fix spec bugs in numberformat.html caused by Unified NumberFormat

---

spec/datetimeformat.html

Based on https://tc39.es/proposal-intl-extend-timezonename/
The &lt;del&gt; and some &lt;ins&gt; in the spec text is already in latest ECMA402
pending on Stage 4 Advancement in 2021-Dec TC39

Stage 4 PR for proposal-intl-extend-timezonename

---

spec/datetimeformat.html

fixes #511 
There's another alternative that I considered which is adding `hourCycle` to Table 4, but that would be a rather big change as `hourCycle` isn't technically a date/time formatting parts, just preferences.
Since it's not in Table 4, `BasicFormatMatcher` basically doesn't do anything with it, but `BestFitFormatMatcher` technically can since it's impl-dependent

Normative: Add hourCycle to opt before passing to FormatMatcher

---

spec/displaynames.html

Based on https://tc39.es/intl-displaynames-v2/
pending on TC39 2021-Dec decision

Normative: add intl-displaynames-v2

---

spec/datetimeformat.html
spec/numberformat.html

```
warning: trailing spaces are not allowed (spelling) at spec/datetimeformat.html:152:54:
150 |           1. Assert: _hour12_ is *undefined*.
151 |         1. Set _dateTimeFormat_.[[HourCycle]] to _hc_.
> 152 |         1. Set _formatOptions_.[[hourCycle]] to _hc_. 
|                                                      ^
153 |         1. Let _matcher_ be ? GetOption(_options_, *"formatMatcher"*, *"string"*, &laquo; *"basic"*, *"best fit"* &raquo;, *"best fit"*).
154 |         1. Let _dateStyle_ be ? GetOption(_options_, *"dateStyle"*, *"string"*, &laquo; *"full"*, *"long"*, *"medium"*, *"short"* &raquo;, *undefined*).
155 |         1. Set _dateTimeFormat_.[[DateStyle]] to _dateStyle_.
warning: literal Number or BigInt values should be followed by <sub>𝔽</sub> or <sub>ℤ</sub> …
```

Editorial: Fix ecmarkup warnings

---

spec/numberformat.html

Add "tnsa" to the table of numbering systems with simple digit mappings. The
Tangsa script ("Tnsa") is a new addition in Unicode 14.
Also see: <https://github.com/unicode-org/cldr/pull/1326>

Normative: Add new numbering system "tnsa"

---

spec/relativetimeformat.html

Fixes a PDF rendering glitch. This should ideally land before cutting the 2022 edition.
before | after
-- | --
scrollbar in rendered PDF:<br>![before](https://user-images.githubusercontent.com/1199584/158880854-6aa06a0b-9ecc-4fd2-ac49-bece29ebac22.png) | no scrollbar:<br> ![after](https://user-images.githubusercontent.com/1199584/158880869-ab5fbb8f-063c-4dfb-b841-45dd05778f39.png)

Editorial: Refactor an example to eliminate horizontal scrolling

---

spec/datetimeformat.html

Editorial: Add missing ! to Call invocations.

---

spec/displaynames.html

Make it clear "_" is not acceptable for calendar code

Normative: Disallow '_' for calendar , referring to UTS35

---

spec/datetimeformat.html

The field is set, read, and then immediately overwritten, without any other possible use in between.

Editorial: Only set dtf.[[HourCycle]] once.

---

spec/numberformat.html

"Negative zero" cannot be expressed with an ECMA262 mathematical value,
but it may be expressed with an ECMA262 Number value. Update new
references to "negative zero" to use an appropriate type. Update
corresponding references to "zero" to avoid comparing mathematical
values with Number values.
/cc @bakkot

Editorial: correct references to negative zero

---

spec/datetimeformat.html
spec/displaynames.html
spec/intl.html
spec/listformat.html
spec/locale-sensitive-functions.html
spec/locale.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html

This is a group of commits from the following respective Pull Requests where I had to resolve conflicts locally. The commit names are preserved.
Closes #630 
Closes #660 
Closes #610

Editorial: Merge PRs for 2022

---

spec/datetimeformat.html

Closes #602
commit f18b0544c9ea8c6f4df891c1e536e0c5e23708af
Merge: 0836725 233d29c
Author: Leo Balter <leonardo.balter@gmail.com>
Date:   Mon Mar 28 01:48:44 2022 -0700
Merge branch 'master' into 2021-08-cleanup-InitializeDateTimeFormat
commit 08367259e1131379c073c5ef5f8fff871c2f3260
Author: Richard Gibson <richard.gibson@gmail.com>
Date:   Tue Aug 17 18:55:23 2021 -0400
Editorial: Simplify {date,time}Style vs. explicit component checking
commit a1f6ff3bd3246f4e23eb70ddddf7abb6cf722b83
Author: Richard Gibson <richard.gibson@gmail.com>
Date:   Tue Aug 17 18:46:55 2021 -0400
Editorial: Update InitializeDateTimeFormat to use more standard conventions

Editorial conflicts resolution

---

spec/locales-currencies-tz.html

Minor issue I noticed while looking over recent changes to the spec. In `IsWellFormedCurrencyCode`, the creation of the `normalized` string was moved lower in the AO, after the step to check its length.

Editorial: Don't refer to 'normalized' in IsWellFormedCurrencyCode before it is set

---

spec/datetimeformat.html

Ref #662
* Avoid alias overloading
* Condense steps
* Better localize access

Editorial: Cleanup InitializeDateTimeFormat

---

spec/numberformat.html

* Align construction of a String of repeated code units with ECMA-262
* Align mathematical formulas and character escaping with ECMA-262
* Refer to String elements as "code point" rather than "character"
* Replace improper use of "let" with "set"

Editorial: Update NumberFormat to conform with conventions

---

spec/collator.html

* Align with ECMA-262 [String.prototype.localeCompare](https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.localecompare).
* Reference _collator_ properties (with correct data type).
* Link to UTS \#35.
* Elaborate on "base letter" and provide more examples.
* Clarify the effects of [[Sensitivity]] by switching to a table.

Editorial: Cleanup CompareStrings

---

spec/collator.html
spec/datetimeformat.html
spec/displaynames.html
spec/listformat.html
spec/locale.html
spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/segmenter.html

cf. https://github.com/tc39/ecma402/pull/687#discussion_r888113770
Use of privileged language values in abstract operation arguments is bad form. The generally preferred alternative is to use spec enum values, but [Temporal GetOption](https://tc39.es/proposal-temporal/#sec-getoption) currently uses an alternative approach that directly references [Types](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-data-types-and-values).
I'm not sure which we we want to go here, so I took the Temporal Type-reference approach in the first commit and the conventional ECMA-262 spec-enum-approach in the second for easy adoption of either. I'm interested to hear others' opinions.
Note also that Temporal will move GetOption into ECMA-262, so this is really a question …

Editorial: Replace use of privileged language values in GetOption

---

.github/workflows/deploy.yml

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> `[]`… Ranges can only include `a-z`, `A-Z`, and `0-9`.

Meta: Replace use of prohibited character range

---

spec/datetimeformat.html

Address https://github.com/tc39/ecma402/issues/692

Normative: Remove order check in PartitionDateTimeRangePattern

---

spec/locales-currencies-tz.html

As per the [definition](https://tc39.es/ecma402/#sec-case-sensitivity-and-case-mapping).

Editorial: Consistently use "match for"

---

package-lock.json
package.json
spec/annexes.html
spec/datetimeformat.html
spec/locales-currencies-tz.html

This makes some editorial changes as a result of https://github.com/tc39/ecma262/pull/2781:
- ECMA-262 now has its own DefaultTimeZone operation, so ECMA-402 should note that it supersedes the ECMA-262 one.
- The LocalTZA operation is gone from ECMA-262, so instead use the GetNamedTimeZoneOffsetNanoseconds operation in ToLocalTime.
- GetNamedTimeZoneOffsetNanoseconds encapsulates the requirement to use best-available time zone information, so we can remove one instance of that language and simplify ToLocalTime by calculating the local time regardless of calendar.
- Add structured headers to DefaultTimeZone and ToLocalTime while we're at it.
Closes: #684

Editorial: Adapt to ECMA-262 DefaultTimeZone

---

spec/locales-currencies-tz.html

Address https://github.com/tc39/ecma402/issues/702 and needed by https://github.com/tc39/proposal-intl-duration-format/pull/122

Normative: Add "microsecond" and "nanosecond" to IsSanctionedSingleUnitIdentifier

---

package-lock.json
package.json
spec/datetimeformat.html
spec/locales-currencies-tz.html
spec/negotiation.html

This bumps ecmarkup, which now includes a lint for variables being declared before being used. I've marked two sites which appear to be introducing a variable as doing so, and corrected a typo in a third place.
There's [another place](https://github.com/tc39/ecma402/blob/469814ca60a2d5e1283e7caabf038393f55a44d8/spec/negotiation.html#L178) which refers to a variable which doesn't appear to be defined anywhere, but I couldn't figure out what that was supposed to be doing, so I've left it alone. That should cause this to fail CI. Please feel free to push up a commit fixing that issue before landing this.
Edit: oh, looks like lint rules aren't enforced in CI, so it's not failing the build. You might want to do that - it's just a matter of adding `--strict` to the build command.
(Ignore the …

Meta: bump ecmarkup to 16.0.0

---

spec/negotiation.html

* Use a single step for testing the "specified non-default option is supported" condition.
* Use conventional patterns for concatenating and determining the length of strings.
* Use "set _x_ to" rather than "let _x_ be" for *updating* a spec alias.

Editorial: Tweak ResolveLocale for clarity

---

spec/locales-currencies-tz.html

tzdata 2022f using vanguard format made "GMT" a zone and "Etc/GMT" a link to "GMT". Rearguard format still has this the other way around, i.e. "Etc/GMT" is a zone and "GMT" a link to "Etc/GMT". Because we don't control if vanguard or rearguard format is used by an implementation, the `CanonicalizeTimeZoneName` operation should canonicalise both "Etc/GMT" and "GMT" to "UTC".

Normative: Canonicalise "GMT" to "UTC"

---

spec/numberformat.html

Add "kawi" and "nagm" to the table of numbering systems with simple digit mappings. Both are new additions from Unicode 15.
Also see: unicode-org/cldr#2041

Normative: Add new numbering systems "kawi" and "nagm"

---

CONTRIBUTING.md

* Use consistent spelling for "ECMA-262", "ECMA-402", "task group" (vs. "(sub)committee"), and "specification" (vs. "standard" or "language").
* Link to HEAD to avoid embedding the primary branch name.
* Add internal and external links.
* Define "i18n".

Meta: Cleanup CONTRIBUTING.md

---

.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/config.yml

Keep the guidelines link (but correct its target to ECMA-402 CONTRIBUTING.md) and add a template specifically for proposals (with a guidelines link of its own).

Meta: Fix issue templates

---

spec/listformat.html

https://github.com/tc39/ecma262/pull/3021 proposes removing optionality from the second argument

Editorial: Explicitly provide all GetIterator arguments

---

spec/datetimeformat.html

Fix the issue that missing [[RangePattern]], [[DateStyle]], and [[TimeStyle]] for Intl.DateTimeFormat
Close #762

Editorial: Add missing internal slots to internalSlotsList

---

spec/datetimeformat.html

This commit removes the `!` from two AO calls that return regular values, not abrupt completions.
From a quick look it seems that there are quite a few other AOs that cannot throw but still are called with `!` in the spec, so it's probably worth a full scrub at some point. For this PR I'm only worried about calls that I noticed while reviewing a Temporal PR.

Editorial: remove `!` from two calls to AOs that can't throw

---

spec/datetimeformat.html

This PR includes a few minor updates to spec text about time zone identifiers that I noticed while preparing the Time Zone Canonicalization proposal:
* Fixes an inconsistency between text in [#sec-time-zone-names](https://tc39.es/ecma402/#sec-time-zone-names) (which requires IANA Time Zone Database) and text in two AOs that implies that such support is optional. This PR replaces the latter optional-implying text with the text from #sec-time-zone-names.
* Renames `_timeZone_` variable to `_timeZoneIdentifier_` when it's guaranteed to be a string.
* Replaces "name" with the more precise "identifier" in a few places.

Editorial: update time zone identifier text

---

spec/intl.html
spec/locales-currencies-tz.html

Plan to suggest moving to Stage 4 in Nov 2022
https://github.com/tc39/proposal-intl-enumeration
It is already implemented in Chrome m99, Safari 15.4 and Firefox 93.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/supportedValuesOf#browser_compatibility

Normative: Stage4 PR for proposal-intl-enumeration

---

spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html

https://github.com/tc39/proposal-intl-numberformat-v3

Normative: Integrate Intl NumberFormat v3 into ECMA-402

---

spec/datetimeformat.html

Some improvements noticed while reviewing #770
* Better align with conventions
* Consolidate practical-equality determination
* Improve alias names
* Add clarifying note

Editorial: Improve PartitionDateTimeRangePattern

---

spec/annexes.html
spec/conformance.html
spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/locales-currencies-tz.html
spec/overview.html

fix #641 
Replaced phrases like "current version of the ECMAScript Internationalization API Specification" with "this specification" where appropriate, with some edits to wording of surrounding sentences to avoid ambiguity between references to _this_ specification and references to ECMA-262. 
Thought: ECMA-419 introduces 262 with this sentence:
> This Standard does not make any changes to the ECMAScript language as defined by ECMAScript Language Specification (ECMA-262)
and then subsequently refers to it as ECMA-262. Given how often references to 262 appear in 402, I'm tempted to follow their lead.

Editorial: Regularize self-references to ECMA-402

---

spec/negotiation.html

Ref https://github.com/tc39/ecma402/pull/785#discussion_r1212190466
* Use a locale for which the default calendar does not sort first alphabetically.
* Use a locale that is more than just a language identifier.
* Replace vague "would therefore at least include…" language with a complete Record example.

Editorial: Improve the [[LocaleData]] explanation

---

spec/collator.html

Fix #256 
(see also corresponding MDN PR: https://github.com/mdn/content/pull/27274)

Editorial: added explanatory note on appropriate usage of `search` collation

---

spec/collator.html

Corrects a recent botch in collator spec.

Editorial: Two links were in Markdown syntax rather than actual HTML

---

spec/conventions.html

fix #655 
Added %SegmentIteratorPrototype% and %SegmentsPrototype% to the well-known intrinsics table, giving them no global name (as with analogous-seeming intrinsics in ECMA-262, i.e. %StringIteratorPrototype%, %RegExpStringIteratorPrototype%, etc.)
Let me know if this one should be considered normative.

Editorial: Added %SegmentIteratorPrototype% and %SegmentsPrototype% to the well-known intrinsics table

---

spec/numberformat.html

fix #585 
Unclear what the consensus was on increasing max fractional digits to match 262, but if we're doing it this PR does it.

Normative: raised minimum/maximum fractional digits from 20 to 100

---

spec/numberformat.html

The second commit is a normative reordering of property sequence; the first commit is a supporting editorial change that should land in some form even if the normative change is rejected.

Normative: Reorder NF resolved option "roundingPriority"

---

spec/conventions.html

Better aligns the [ECMA-402 Well-Known Intrinsic Objects table](https://tc39.es/ecma402/#sec-402-well-known-intrinsic-objects) with its [referent in ECMA-262](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-well-known-intrinsic-objects).

Editorial: Remove extraneous periods

---

spec/datetimeformat.html
spec/locale-sensitive-functions.html
spec/negotiation.html
spec/numberformat.html

Replaced all non-standard 'increase _x_ by _y_' and 'decrease _x_ by …' statements with standard 'Set _x_ to _x_ + _y_' and 'set _x_ to _x_ - _y_' statements. fix #677.

Editorial: Replaced all non-standard 'increase _x_ by _y_' and 'decrease _x_ by …' statements 

---

spec/numberformat.html
spec/pluralrules.html

Split the editorial fix from https://github.com/tc39/ecma402/pull/811
1. Add text to explain ComputedRoundingPriority in section "15.4 Properties of Intl.NumberFormat Instances" https://tc39.es/ecma402/#sec-properties-of-intl-numberformat-instances and "16.4 Properties of Intl.PluralRules Instances
https://tc39.es/ecma402/#sec-properties-of-intl-pluralrules-instances
2. Add ComputedRoundingPriority to Intl.PluralRules https://tc39.es/ecma402/#sec-intl.pluralrules Without this, the spec is not implementable because InitializePluralRules call "SetNumberFormatDigitOptions(pluralRules, options, +0𝔽, 3𝔽, "standard")." and SetNumberFormatDigitOptions assume the intlObj has [[ComputedRoundingPriority]]

Editorial: Fix Intl.PluralRules after the merging of PR 811

---

meetings/notes-2023-01-12.md
meetings/notes-2023-02-09.md
meetings/notes-2023-03-09.md
meetings/notes-2023-04-06.md
meetings/notes-2023-05-04.md
meetings/notes-2023-06-01.md
meetings/notes-2023-06-29.md
meetings/notes-2023-08-03.md
meetings/notes-2023-09-07.md

According to https://github.com/tc39/notes/blob/main/delegates.txt, @ben-allen is BAN not BEN.
When acronyms change, precedent is to update old notes. I believe we last did this when Michael Saboff changed from MS to MLS.

Meta: Update BEN to BAN

---

spec/annexes.html
spec/datetimeformat.html
spec/locales-currencies-tz.html

Fixes #683
This aligns with ECMA-262, and therefore removes the DefaultTimeZone override.
Example time zones that will now be accepted: [Temporal |TimeZoneUTCOffsetName|](https://tc39.es/proposal-temporal/#prod-TimeZoneUTCOffsetName)
* "+00"
* "-00"
* "−00"
* "+0000"
* "-0000"
* "−0000"
* "+00:00"
* "-00:00"
* "−00:00"
* "+2359"
* "+23:59"
* "-2359"
* "-23:59"
* "−2359"
* "−23:59"

Normative: Allow UTC offset time zones

---

spec/datetimeformat.html

While hour12 is  false, let hourCycle to be alwasyt 'h23' but not 'h24'.
The current logic is not reasonable. We see no region in the CLDR use  h24 hour cycle as default.  While we set a hour12: false on a 12 hour system region (which use 1:00 - 12:59), we should set to h23 instead of h24
We need to make this change
so while hour12 is false on 'en' locale, it will be set to h23 instead of h24
but also while hour12 is true on 'ja' locale, it will be set to h11 but not h12.
Address https://github.com/tc39/ecma402/issues/402

Normative: Change the hourCycle default logic

---

spec/numberformat.html
spec/pluralrules.html

Fixing issues created by https://github.com/tc39/ecma402/pull/768 and additional issues about 'order' related to number format v3 and option read/ resolvedOptoins()
1.  Move the reading of "roundingPriority" from before reading "roundingIncrement" to after reading "roundingMode" so these three fields are read in alphabetic order. https://tc39.es/ecma402/#sec-setnfdigitoptions
2. Move the output order of "roundingIncrement" from after output "roundingMode" to before that so these two fields are read in alphabetic order in the resolvedOptions of both Intl.NumberFormat and Intl.PluralRules. https://tc39.es/ecma402/#sec-intl.numberformat.prototype.resolvedoptions https://tc39.es/ecma402/#sec-intl.pluralrules.prototype.resolvedoptions
3. Move the output of "roundingPriority" from after …

Normative: Fix order of rounding* option reads and resolvedOptions()

---

spec/collator.html
spec/datetimeformat.html
spec/listformat.html
spec/locale.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/numberformat.html
spec/relativetimeformat.html

Align with ECMA-262:
* https://github.com/tc39/ecma262/commit/2df27d363f9622193d5100d769039dde47a9fa64
* https://github.com/tc39/ecma262/pull/2152

Editorial: Use consistent wording for List interactions

---

spec/locale-sensitive-functions.html

This style follows other "length" properties in this spec and the ECMAScript spec.

Editorial: Remove a paragraph for the length property of String.prototype.localeCompare

---

spec/collator.html
spec/conventions.html
spec/datetimeformat.html
spec/displaynames.html
spec/listformat.html
spec/locale-sensitive-functions.html
spec/locale.html
spec/numberformat.html
spec/overview.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/segmenter.html

Closes #842.
Not sure if the same naming scheme is appropriate for `%SegmentIteratorPrototype%` and `%SegmentsPrototype%`, but happy update those as well if wanted.

Editorial: Prefix names of intrinsics

---

spec/locale.html

Normative: Canonicalize value of extension in ApplyUnicodeExtensionToTag

---

spec/annexes.html
spec/collator.html

"th" locale in CLDR collation rule default ignorePunctuation to true instead of false so we need to get tht default value from the locale data instead of always false.
Address https://github.com/tc39/ecma402/issues/832
th CLDR rule is in 
https://github.com/unicode-org/cldr/blob/main/common/collation/th.xml#L17
```
[alternate shifted]
```
@anba @sffc @ben-allen  @gibson042

Normative: Allow locale based ignorePunctuation default

---

spec/datetimeformat.html

Used "of the current row" instead of "of the row" when appropriate, to match rest of 402, also fixed unclear wording for FormatDateTimePattern instruction 15.f

Editorial: regularized wording for table iteration in datetimeformat

---

spec/negotiation.html

Replaced with assertion since all the key come from internal slots that are already all in lowercase ASCII.
This issue is mentioned by @anba in https://github.com/tc39/ecma402/pull/846#r1428263375

Editorial: Remove unnecessary lowercase conversion of key

---

.github/workflows/publish-biblio.yml
biblio/README.md
biblio/package.json
scripts/publish-biblio.sh

Fixes https://github.com/tc39/ecma402/issues/710. This is just a copy-paste of the relevant files from ecma262 with a find-replace of 262 with 402. It also adds a `LICENSE.md` to the top level of the repo so that it can use the same license for the published biblio package.
In the linked issue @ljharb said he'd need to publish it manually first, but I'm not sure why; I think automation tokens can publish the first version of a package?

Meta: publish biblio in github actions

---

spec/collator.html
spec/datetimeformat.html
spec/displaynames.html
spec/listformat.html
spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/segmenter.html

This has been bugging me for quite a while.
* Rename _dataLocaleData_ aliases to the more accurate _resolvedLocaleData_
* Update the return value to include locale data rather than its lookup key
* Capitalize the return value static field names

Editorial: Refactor ResolveLocale to simplify calls

---

scripts/publish-biblio.sh

Fix publish-biblio.sh to match actual build

---

spec/locales-currencies-tz.html

This is already required:
* LookupMatcher can return { [[locale]]: DefaultLocale(), ... }.
* ResolveLocale uses that result's [[locale]] as the name of a field in its _localeData_ argument and asserts that the corresponding value is a Record.
* The _localeData_ argument to ResolveLocale is generally provided from the value of a service constructor's [[LocaleData]] slot.
* "Internal slots of Service Constructors" constrains those slots to be Records "that have fields for each locale contained in [[AvailableLocales]]", and constrains their [[AvailableLocales]] slots to include only language tags that "must not have a Unicode locale extension sequence".
Therefore, if DefaultLocale() *were* to return a value with a Unicode locale extension sequence, use of it in ResolveLocale would fail to …

Editorial: Document that DefaultLocale() returns must not include a "-u-" extension

---

spec/negotiation.html

Explanatory note added to address concerns raised in #685 
fix #685

Editorial: Best available locale documentation

---

spec/datetimeformat.html
spec/numberformat.html

Rebased 3-1-24, and updated to include @gibson042 suggestion to improve readability of `SetNumberFormatDigitOptions` AO in `Intl.NumberFormat`
Fix #458 
Refactored several cases from  
1. If not *undefined*, then 
a. X
2 Else,
a. Y
with
1. If *undefined*, then 
a. Y
2. Else,
a. X
and 
1. If not *undefined*, then
a. Return X.
2. Return Y.
to 
1. If *undefined*, then
a. Return Y.
2. Return X.

Editorial: Removed several unnecessary double negatives

---

spec/negotiation.html

Per [RFC 4647 section 3.4 - Lookup](https://www.rfc-editor.org/rfc/rfc4647.html#section-3.4),
> Single letter or digit subtags (including both the letter 'x', which introduces private-use sequences, and the subtags that introduce extensions) are removed at the same time as their closest trailing subtag.
This is relevant for a requested locale such as "en-x-y-z-foo", which should be truncated first to "en-x-y-z" and then to "en" ("y" is removed at the same time as its closest trailing subtag "z" and "x" is removed at the same time as its closest trailing subtag "y", which means all three are removed in one step).
However, the change is still editorial because BestAvailableLocale is never called with _availableLocales_ that would contain a language tag like "en-x-y".

Editorial: Better align BestAvailableLocale with BCP 47

---

spec/overview.html

gh-424 is more comprehensive than gh-342, which is specific to DateTimeFormat

Editorial: Retarget the link explaining lack of parsers

---

spec/annexes.html
spec/collator.html
spec/datetimeformat.html
spec/displaynames.html
spec/listformat.html
spec/locale-sensitive-functions.html
spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/segmenter.html

Best reviewed commit-by-commit.
[RFC 4647 section 2.3](https://www.rfc-editor.org/rfc/rfc4647.html#section-2.3) defines "language priority list" as "_a prioritized or weighted list of language ranges_", and corresponds to _requestedLocales_ in various ECMA-402 operations.
[RFC 4647 section 3](https://www.rfc-editor.org/rfc/rfc4647.html#section-3) differentiates "matching schemes" applying such lists against available locales into "filtering" (producing zero or more matches) and "lookup" (producing exactly one match). [Language Tags and Locale Identifiers for the World Wide Web](https://www.w3.org/International/core/langtags/#sec-locale-vs-language) reinforces their significance ("_Specifications that define operations on language tags or locale values using matching MUST specify whether …

Editorial: Refactor Locale and Parameter Negotiation to better align with BCP 47

---

spec/annexes.html
spec/datetimeformat.html
spec/intl.html
spec/locales-currencies-tz.html

This PR updates ECMA-402 spec text to align with current ECMA-262 terminology and AOs for time zone identifiers. Changes include:
* Replaces `DefaultTimeZone`,  `CanonicalizeTimeZoneName`, and `IsValidTimeZoneName` with calls to current ECMA-262 abstract operations.
* Refactors `AvailableCanonicalTimeZones`  to call new ECMA-262 AOs, and renames it to `AvailablePrimaryTimeZoneIdentifiers`.
* Adds a `GetAvailableNamedTimeZoneIdentifier` AO Temporal will eventually merge into ECMA-262, but it's not there yet so we need a copy here.
* Replaces `#sec-time-zone-names` with a "Use of the IANA Time Zone Database" section that extends ECMA-262's `#sec-time-zone-identifiers` section.
* Adds a few paragraphs of editorial recommendations (borrowed from Temporal) about managing updates and builds of …

Editorial: align time zone identifier text and AOs with ECMA-262

---

spec/collator.html
spec/datetimeformat.html
spec/locales-currencies-tz.html
spec/numberformat.html

Editorial: Inspired by https://github.com/tc39/ecma402/pull/869/, regularize comparison language by replacing "is equal to" and "is not equal to" with "is" and "is not" as appropriate.

Editorial: Replace irregular "is equal to" language

---

spec/negotiation.html

* Adds a prose description explaining treatment of brace-wrapped placeholders and adjacent literal text in converting a String pattern into an equivalent List of Records.
* Renames spec aliases (_beginIndex_ → _placeholderStart_, _endIndex_ → _placeholderEnd_, _p_ → _placeholderName_).
* Adopts ECMA-262 phrasing conventions (e.g., "the [substring](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#substring) of _S_ from _inclusiveStart_ [to _exclusiveEnd_]" and `<`/`≤`/`≥`/`>` operators).
* Reduces unnecessary repetition (e.g., "If _beginIndex_ \> _nextIndex_, then Let _literal_ be the substring of _pattern_ from _nextIndex_ to _beginIndex_ and Append the Record { [[Type]]: **"literal"**, [[Value]]: _literal_ } to _result_." → "Let _literal_ be the substring of …

Editorial: Refactor PartitionPattern for simplicity and comprehensibility

---

spec/locales-currencies-tz.html

See tc39/ecma262#3299. This is the language preferred by the editors.

Editorial: Use "sorted according to lexicographic code unit order"

---

spec/collator.html
spec/datetimeformat.html
spec/listformat.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/numberformat.html
spec/relativetimeformat.html

`Intl.DateTimeFormat` used "record" and "list" to refer to Records and List should have been used. This PR capitalizes those words as appropriate.

Editorial: capitalized previously-uncapitalized instances of "list" and "record" as appropriate

---

spec/locale.html
spec/locales-currencies-tz.html
spec/negotiation.html

* Rename ApplyOptionsToTag to UpdateLanguageId, move its locale id syntax validation out to the (sole) call site, and handle each overriding datum in its own single block.
* Rename ApplyUnicodeExtensionToTag to MergeLocaleData.
* Refactor InsertUnicodeExtensionAndCanonicalize(_locale_, _extension_) into InsertUnicodeExtensionAndCanonicalize(_locale_, _attributes_, _keywords_) (constructing the new -u- extension inline).
* Fix a spec bug in CanonicalizeUnicodeLocaleId.

Editorial: Clarify operations related to merging locale data

---

spec/intl.html
spec/locale.html
spec/locales-currencies-tz.html
spec/negotiation.html

AvailableCalendars should return all possible aliases, so that other places in the spec (e.g. in the future, validating a string calendar ID in Temporal) can use them to determine whether a given input value is valid. This input value can subsequently be canonicalized by another abstract operation, CanonicalizeUValue, which we can use in several other places.
In Intl.supportedValuesOf(), on the other hand, we should not return all possible aliases, so we filter them out using CanonicalizeUValue before returning the list of AvailableCalendars codes as an array to the caller.
See https://github.com/tc39/proposal-intl-enumeration/pull/49. This is the part of that PR that I consider relevant for the future integration of Temporal. The time zone parts were already done as part of #876. If …

Editorial: Replace AvailableCanonicalCalendars with AvailableCalendars

---

spec/negotiation.html

`Type()` is kind of a weird operation; it's not totally clear what `Type` would return for an arbitrary Record. For example, [Completion Records](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-specification-types) are listed as specification types, so would `Type(_cr_)` be "Record" or "Completion Record"? https://github.com/tc39/ecma262/pull/3339 will clarify this, but will do so by precisely defining the domain of input to be only ES language types, not specification types.
In any case, it's also not necessary to use the macro here; the prose is easier to read anyway. This was the only use of this AO in 402.

Editorial: replace use of Type macro

---

spec/datetimeformat.html
spec/listformat.html
spec/locale-sensitive-functions.html
spec/locales-currencies-tz.html
spec/negotiation.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html

Fixes a couple of rebase errors. Also reverts attempts to address review feedback ("pattern" instead of "format" for some records), because the changes were largely unfinished and actually using "pattern" would result in equally confusing code like `pattern.[[pattern]]` which doesn't seem like an improvement when compared to `format.[[pattern]]`. For example see  [FormatDateTimePattern](https://tc39.es/ecma402/#sec-formatdatetimepattern), which has `format` and `pattern` arguments.
Fixes #899.

Editorial: Fix various rebase errors

---

spec/locales-currencies-tz.html

This proposed change resolves #825 by adding normative spec text to clarify how ECMA-402 implementations should decide which IANA time zone IDs should be primary vs. non-primary. This will enable more consistency between ECMAScript implementations and prevent future divergence.
This PR also accommodates to web reality by aligning ECMA-402 with CLDR and ICU. This should make it easier for all ECMAScript engines to comply with the spec while still being able to use ICU. 
This PR is stacked on #876, so please ignore the first commit when reviewing this PR.
Note that the problem of out-of-date primary IDs for renamed Zones (like Asia/Calcutta) is out of scope to this PR, because the [spec](https://tc39.es/ecma402/#sec-canonicalizetimezonename) already requires current IDs, and there's already …

Normative: specify time zone ID requirements to reduce divergence between engines

---

docs/style-guide.md

Toward #578
1795b9d9db31c28c869da6d859889b2f39b4c9c6 inspired by https://github.com/tc39/ecma402/issues/578 
29e183bd51c30fc5082b846ec8abcf42d7492caa inspired by https://github.com/tc39/proposal-intl-duration-format/issues/163

Meta: Update style guide to discuss preferred orderings of elements

---

spec/locales-currencies-tz.html

Drive-by change:
- Fix indentation for `StringSplitToList`.

Editorial: Remove stray emu-clause close tag.

---

spec/locale.html

Rename the internal slot name to avoid confusion with the `[[RelevantExtensionKeys]]` for Intl service constructors, because `Intl.Locale` isn't an Intl service constructor.

Editorial: Rename [[RelevantExtensionKeys]] to [[LocaleExtensionKeys]] for %Intl.Locale%

---

spec/locale.html
spec/locales-currencies-tz.html

Add `GetLocaleBaseName` to avoid repeating the same steps to extract the `unicode_language_id` parts of a `unicode_locale_id`. The abstract operation is named to `GetLocaleBaseName` to match the accessor property `Intl.Locale.prototype.baseName`.

Editorial: Add GetLocaleBaseName abstract operation

---

spec/annexes.html
spec/numberformat.html

This PR allows for locale data other than ISO 4217 for determining the number of fractional digits to be used when formatting currency values.
In some applications ISO 4217 is most appropriate, in some CLDR data, and in some neither is best. See https://github.com/tc39/ecma402/pull/921#issuecomment-2313173054
Resolves #134
This PR makes the `CurrencyDigits` AO implementation-defined.

Normative: Allow use of non-ISO 4217 data in `CurrencyDigits` AO

---

spec/numberformat.html

Previously this data was inappropriately used to set the number of fractional digits displayed when formatting currency values in scientific, engineering, and compact notations. Fix #912.

Normative: When formatting currency values, only use data on the number of minor units used to display that currency when using standard notation.

---

spec/pluralrules.html

fix https://github.com/tc39/ecma402/issues/578
This change follows the ordering suggested by @zbraniecki in https://github.com/tc39/ecma402/issues/578#issuecomment-873725419

Normative: Explicitly designate sort order for plural categories returned by Intl.PluralRules.prototype.resolvedOptions

---

spec/datetimeformat.html
spec/relativetimeformat.html

Fix https://github.com/tc39/ecma402/issues/819
This fixes a spec bug; as far as I can tell, all actually existing implementations do this the right way rather than the specified way. Will change title to start with "Normative:" if this category of fix requires TG1 consensus.

Normative: Fix bug with RelativeTimeFormat and DateTimeFormat not correctly passing "numberingSystem" option to NumberFormat

---

spec/numberformat.html

There are no reason we need to put the "Let _currency_ be _numberFormat_.[[Currency]]." line in a separate if block. Move that down

Editorial: Simplify PR925

---

spec/pluralrules.html

`GetOperands` was only called from the `ResolvePlural` AO, which immediately passed the Record returned by `GetOperands` to the implementation-defined PluralRuleSelect AO. The revised version of `ResolvePlural` directly passes `PluralRuleSelect` the decimal String which was previously parsed by `GetOperands`. Implementations of `PluralRuleSelect` may (or may not) use something like `GetOperands` to determine the correct plural category.
fixes https://github.com/tc39/ecma402/issues/635

Editorial: Inlined Intl.PluralRules's GetOperands AO.

---

spec/locale.html
spec/locales-currencies-tz.html

Replace complex substring descriptions with better use of subtag references and existing operations.

Editorial: Clarify and simplify GetLocaleVariants and IsStructurallyValidLanguageTag

---

package-lock.json
package.json
spec/segmenter.html

`CreateIterResultObject` has been renamed to `CreateIteratorResultObject`.

Meta: Update ecmarkup and ecma262-biblio

---

spec/numberformat.html

This makes the following editorial changes to `Intl.NumberFormat`'s `CollapseNumberRange` AO:
* Make `CollapseNumberRange` take an `Intl.NumberFormat` as a parameter to enable locale-specific modifications of the `result` list.
* Explicitly state that `CollapseNumberRange` can potentially add spacing characters, as in the LDML `Range Pattern Processing` instructions. See https://unicode-org.github.io/cldr/ldml/tr35-numbers.html#Range_Pattern_Processing
Fix #935

Clarify `CollapseNumberRange` AO

---

spec/collator.html
spec/datetimeformat.html
spec/displaynames.html
spec/listformat.html
spec/locale.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/segmenter.html

Resolves the following aspects of #405:
Placed Prototype Object properties in the following order for all Intl Objects:
1. Intl._Foo_.prototype.constructor
2. Intl._Foo_.prototype.resolvedOptions ()
3. Intl._Foo_.prototype [ %Symbol.toStringTag% ]
4. ..._Foo_-specific properties in alphabetic order...
Gathered all Abstract Operations associated with each Object into the Abstract Operations section for that Object. Previously Intl.DateTimeFormat, Intl.Locale, and Intl.NumberFormat had several Abstract Operations appear inside the constructor clauses of those Objects.

Editorial: Arrange contents consistently

---

spec/numberformat.html

Unicode 16 added 8 new numbering systems for the newly added 5,185 new characters, including 3,995 additional Egyptian Hieroglyph characters plus seven new scripts, seven new emoji characters, and over 700 symbols from legacy computing environments. see https://blog.unicode.org/2024/09/announcing-unicode-standard-version-160.html
CLDR add that in https://github.com/unicode-org/cldr/pull/3658 which will be available in ICU 76
This PR update the ECMA402 spec to include that new numbering systems. 
We should consider merging it after ICU 76.1 is wildely available to implementer. We probably should discuss this in TG2 around Nov. or Dec. 2024.

Normative: Add 8 new numbering systems for Unicode 16

---

spec/durationformat.html
spec/index.html

https://github.com/tc39/proposal-intl-duration-format

Normative: add Intl.DurationFormat

---

spec/durationformat.html

* `emu-format`
* align section order with #923
* replace outdated use of `@@toStringTag` and "abrupt completion"
* improve documentation of internal slots
* simplify `resolvedOptions` and `GetDurationUnitOptions`

Editorial: Clean up DurationFormat

---

spec/durationformat.html

Rather than define _maximumFractionDigits_ and _minimumFractionDigits_ in branches that converge with ! CreateDataPropertyOrThrow, just perform the latter in those branches.
We could also introduce a dedicated operation for use like `Perform SetFractionDigitsForDuration(_nfOpts_, _durationFormat_.[[FractionalDigits]]).`, but I have opted not to do so.

Editorial: Remove some single-use DurationFormat spec aliases

---

spec/annexes.html
spec/collator.html
spec/conventions.html
spec/datetimeformat.html
spec/displaynames.html
spec/durationformat.html
spec/listformat.html
spec/locale.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/segmenter.html

* link to the respective $Type constructor section
* link directly to any appropriate [UTS 35 Key And Type Definition](https://unicode.org/reports/tr35/#Key_And_Type_Definitions_)

Editorial: Update "Properties of $Type Instances" sections

---

spec/numberformat.html
spec/pluralrules.html

Split from #978
* Fix `id` values to align with operation names.
* Refactor spec aliases and parameter types for readability.

Editorial: Clean up NumberFormat

---

spec/segmenter.html

We do not want to use Intl.NumberFormat's internal slots here.

Editorial: Pass `%Intl.Segmenter%` to its invocation of `ResolveOptions`

---

spec/datetimeformat.html
spec/index.html
spec/numberformat.html

Markup: Eliminate usage of <emu-normative-optional>

---

spec/locales-currencies-tz.html

Add a normative note to the DefaultLocale AO to indicate that it can be used as a fingerprinting vector in browser environments.
Fixes #110

Editorial: mark DefaultLocale as a fingerprinting vector

---

spec/locale.html

Fixes #900
test262 PR: https://github.com/tc39/test262/pull/4474

Normative: Add Intl.Locale.prototype.variants

---

spec/overview.html

Normative: Added note about sets of locales for web browser implementations needing to not change as a result of user behaviour

---

spec/collator.html
spec/datetimeformat.html
spec/displaynames.html
spec/durationformat.html
spec/intl.html
spec/listformat.html
spec/locale.html
spec/numberformat.html
spec/pluralrules.html
spec/relativetimeformat.html
spec/segmenter.html

Update descriptions of constructors and prototypes to use `<ul>` elements. This matches the style used in ECMA-262.
The [[Prototype]] is now also always defined, even if it matches the default prototype defined in <https://tc39.es/ecma262/#sec-ecmascript-standard-built-in-objects>. This is also done to mimic definitions from ECMA-262.

Editorial: Use lists to describe Intl constructors and prototypes

---

spec/segmenter.html

The function name must be explicitly specified for methods whose property key is a Symbol value.

Normative: Add missing name property for %IntlSegmentsPrototype%[%Symbol.iterator%]

---

spec/overview.html

This PR uses wording given by [aphillips](https://github.com/aphillips) in https://github.com/tc39/ecma402/issues/1014#issuecomment-3036691499 to more correctly describe the number of known languages. 
fix #1014

Editorial: Update language count given in overview
